# Generated by Django 2.0.5 on 2019-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('body', models.TextField(max_length=600)),
            ],
        ),
    ]
